import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./_providers/redux-provider";
import { DuckDBProvider } from "./_providers/DuckDBContext";
import SideBarLayout from "@/components/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ReduxProvider>
          {/* <DuckDBProvider> */}
             <SideBarLayout>
                {children}
            </SideBarLayout>
          {/* </DuckDBProvider> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
